var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/proto/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.cvpsi._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0l11~c6.js")
R.c("server/chunks/ssr/[root-of-the-server]__13bkri5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0fhx__n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_proto_page_actions_0l74rsf.js")
R.m(91992)
module.exports=R.m(91992).exports
