import { SourceAdapter } from './adapters/types';
import { SecEdgarAdapter } from './adapters/sec';
import { IdxAdapter } from './adapters/idx';
import { createHash, verifyExactMatch, normalizeText } from './verifier';

export interface VerifiedEvidence {
  sourceUrl: string;
  documentHash: string;
  canonicalTextHash: string;
  exactQuote: string;
  verified: boolean;
}

export class CitationPipeline {
  private getAdapter(market: 'US' | 'ID'): SourceAdapter {
    return market === 'US' ? new SecEdgarAdapter() : new IdxAdapter();
  }

  /**
   * Extremely simple HTML stripper for the stub pipeline.
   * In production, this would use a robust parser like JSDOM or Cheerio.
   */
  private extractCanonicalText(html: string): string {
    return html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
  }

  /**
   * Executes the 5-stage citation pipeline.
   * 1. Adapter -> 2. Snapshot -> 3. Canonical Text -> 4. Hash -> 5. Exact Verifier -> Evidence
   * 
   * @param market 'US' or 'ID'
   * @param ticker The company ticker
   * @param llmQuotes The quotes generated by the LLM (mocked for now)
   */
  async executeResearchJob(
    market: 'US' | 'ID', 
    ticker: string, 
    llmQuotes: string[]
  ): Promise<VerifiedEvidence[]> {
    // 1. Adapter
    const adapter = this.getAdapter(market);

    // 2. Snapshot
    const snapshot = await adapter.fetchSnapshot(ticker, '10-Q');

    // 3. Canonical Text
    const canonicalText = this.extractCanonicalText(snapshot.rawBytes);

    // 4. Hash
    const documentHash = createHash(snapshot.rawBytes);
    const canonicalTextHash = createHash(canonicalText);

    // 5. Exact Verifier -> Evidence
    const verifiedEvidence: VerifiedEvidence[] = [];

    for (const quote of llmQuotes) {
      try {
        // This will throw if the quote is not a perfect substring match
        verifyExactMatch(quote, canonicalText);
        
        verifiedEvidence.push({
          sourceUrl: snapshot.sourceUrl,
          documentHash,
          canonicalTextHash,
          exactQuote: quote,
          verified: true
        });
      } catch (error) {
        // Log the failure to the console as required by the spec
        console.error(`\n[PIPELINE BLOCK] Evidence rejected by Exact Verifier:\n${error}`);
      }
    }

    return verifiedEvidence;
  }
}
