import { SourceAdapter } from './adapters/types';
import { MockSecAdapter } from './adapters/mock-sec';
import { MockIdxAdapter } from './adapters/mock-idx';
import { createHash, verifyExactMatch, normalizeText } from './verifier';

export interface VerifiedEvidence {
  sourceUrl: string;
  documentHash: string;
  canonicalTextHash: string;
  exactQuote: string;
  impactSummary: string;
  sourceName: string;
  sourceTier: 'official' | 'secondary';
  publishDate: string | null;
  retrievalTimestamp: string;
  parserVersion: string;
}

export class CitationPipeline {
  constructor(
    private readonly adapters: Record<'US' | 'ID', SourceAdapter> = {
      US: new MockSecAdapter(),
      ID: new MockIdxAdapter(),
    },
  ) {}

  private getAdapter(market: 'US' | 'ID'): SourceAdapter {
    return this.adapters[market];
  }

  /**
   * Extremely simple HTML stripper for the stub pipeline.
   * In production, this would use a robust parser like JSDOM or Cheerio.
   */
  private extractCanonicalText(html: string): string {
    return normalizeText(
      html
        .replace(/<[^>]+>/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'"),
    );
  }

  /**
   * Executes the 5-stage citation pipeline.
   * 1. Adapter -> 2. Snapshot -> 3. Canonical Text -> 4. Hash -> 5. Exact Verifier -> Evidence
   * 
   * @param market 'US' or 'ID'
   * @param ticker The company ticker
   * @param llmQuotes The quotes generated by the LLM (mocked for now)
   */
  async executeResearchJob(
    market: 'US' | 'ID', 
    ticker: string, 
    candidates: Array<{ quote: string; impactSummary: string }>,
  ): Promise<VerifiedEvidence[]> {
    // 1. Adapter
    const adapter = this.getAdapter(market);

    // 2. Snapshot
    const snapshot = await adapter.fetchSnapshot(ticker, '10-Q');

    // 3. Canonical Text
    const rawText = new TextDecoder().decode(snapshot.rawBytes);
    const canonicalText = this.extractCanonicalText(rawText);

    // 4. Hash
    const documentHash = createHash(rawText);
    const canonicalTextHash = createHash(canonicalText);

    // 5. Exact Verifier -> Evidence
    const verifiedEvidence: VerifiedEvidence[] = [];

    for (const candidate of candidates) {
      try {
        // This will throw if the quote is not a perfect substring match
        verifyExactMatch(candidate.quote, canonicalText);
        
        verifiedEvidence.push({
          sourceUrl: snapshot.sourceUrl,
          sourceName: snapshot.sourceName,
          sourceTier: snapshot.sourceTier,
          publishDate: snapshot.publishDate,
          retrievalTimestamp: snapshot.retrievalTimestamp,
          parserVersion: snapshot.parserVersion,
          documentHash,
          canonicalTextHash,
          exactQuote: candidate.quote,
          impactSummary: candidate.impactSummary,
        });
      } catch (error) {
        // Log the failure to the console as required by the spec
        console.error('[PIPELINE BLOCK] Evidence rejected by Exact Verifier:', error);
      }
    }

    return verifiedEvidence;
  }
}
