import fs from 'node:fs';
import path from 'node:path';
import { chromium } from '@playwright/test';

/**
 * Generates real (not JSON-described) PNG fixtures for the M005 OCR/vision
 * eligibility eval by rendering a small HTML page formatted like a filing
 * excerpt and screenshotting it with Playwright (already a devDependency for
 * tests/e2e). These are genuine image bytes a vision model must actually
 * read, not a synthetic-fixture text description. Not real company filings —
 * see PROVENANCE.md alongside the output files.
 */

const outputDirectory = path.join(process.cwd(), 'docs', 'evals', 'M001', 'fixtures', 'vision');

type FixtureSpec = {
  fileName: string;
  html: string;
  candidateQuote: string;
};

const FIXTURES: FixtureSpec[] = [
  {
    fileName: 'pltr-gross-margin-scan.png',
    candidateQuote: 'Gross margin for the quarter was 81.3%, compared to 78.1% in the prior-year period.',
    html: `
      <div style="width:900px;padding:48px;background:#fdfaf3;font-family:Georgia,'Times New Roman',serif;color:#1a1a1a;line-height:1.6;">
        <div style="font-size:13px;letter-spacing:0.04em;color:#555;border-bottom:1px solid #999;padding-bottom:8px;margin-bottom:24px;">
          PALANTIR TECHNOLOGIES INC. &mdash; FORM 10-Q (excerpt)
        </div>
        <p style="font-size:16px;">
          Gross margin for the quarter was 81.3%, compared to 78.1% in the
          prior-year period. Management attributes the improvement to
          continued efficiency gains in commercial deployments.
        </p>
        <div style="font-size:11px;color:#777;margin-top:32px;">Page 14 of 47</div>
      </div>
    `,
  },
  {
    fileName: 'bbri-nim-scan.png',
    candidateQuote: 'Pendapatan bersih meningkat 12,4% dibandingkan periode yang sama tahun lalu.',
    html: `
      <div style="width:900px;padding:48px;background:#fdfaf3;font-family:Georgia,'Times New Roman',serif;color:#1a1a1a;line-height:1.6;">
        <div style="font-size:13px;letter-spacing:0.04em;color:#555;border-bottom:1px solid #999;padding-bottom:8px;margin-bottom:24px;">
          PT BANK RAKYAT INDONESIA (PERSERO) TBK &mdash; Laporan Keuangan (excerpt)
        </div>
        <p style="font-size:16px;">
          Pendapatan bersih meningkat 12,4% dibandingkan periode yang sama
          tahun lalu, didorong oleh pertumbuhan margin bunga bersih (NIM)
          yang stabil di atas 6,0%.
        </p>
        <div style="font-size:11px;color:#777;margin-top:32px;">Halaman 9 dari 32</div>
      </div>
    `,
  },
];

async function main() {
  fs.mkdirSync(outputDirectory, { recursive: true });
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 900, height: 500 } });
    for (const fixture of FIXTURES) {
      await page.setContent(fixture.html);
      const target = path.join(outputDirectory, fixture.fileName);
      await page.locator('div').first().screenshot({ path: target });
      process.stdout.write(`Generated ${path.relative(process.cwd(), target)}\n`);
    }
  } finally {
    await browser.close();
  }

  const provenance = `# Vision Fixture Provenance

These PNG files are Playwright-rendered HTML pages, not real company filings
or scanned documents. They exist to give the M005 OCR/vision eligibility eval
genuine image bytes to transcribe (rather than a JSON description of a
document), without using an actual confidential or copyrighted filing.

Generated by \`scripts/generate-vision-fixtures.ts\` (\`npm run fixtures:vision:generate\`).

| File | Candidate quote a passing vision model must transcribe |
|---|---|
${FIXTURES.map((fixture) => `| \`${fixture.fileName}\` | ${fixture.candidateQuote} |`).join('\n')}
`;
  fs.writeFileSync(path.join(outputDirectory, 'PROVENANCE.md'), provenance);
  process.stdout.write('Generated PROVENANCE.md\n');
}

void main();
